app/views/tasks/index.html.erb

confirm merge_deploy

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.tailwind.css
package.json
postcss.config.js
yarn.lock

feat: add post-css & sass-rails

---

Gemfile
Gemfile.lock
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/_header.html.erb
config/application.rb
config/locales/activerecord/ja.yml
config/locales/views/ja.yml

feat: Supported for i18n

---

app/helpers/application_helper.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/layouts/_flash_messages.html.erb
app/views/layouts/application.html.erb
spec/models/user_spec.rb
spec/system/users_spec.rb

Flash messageの追加
Rspecの日本語対応（一部I18n対応）

07 flash massage

---

app/controllers/codes_controller.rb
app/javascript/editor/editor.bundle.js
app/javascript/editor/editor.mjs
app/models/code.rb
app/models/user.rb
app/views/codes/new.html.erb
db/migrate/20240812024853_create_codes.rb
db/migrate/20240812024954_add_user_ref_to_code.rb
db/schema.rb
spec/factories/codes.rb
spec/models/code_spec.rb
tailwind.config.js

09 code save

---

app/javascript/editor/editor.bundle.js
app/javascript/editor/editor.mjs
app/javascript/editor/live_frame.js
app/views/codes/_editor.html.erb

feat: code preview func for HTML

---

Gemfile
Gemfile.lock
app/uploaders/image_uploader.rb
config/initializers/carrierwave.rb

feat: add amazonS3 only public

---

config/initializers/carrierwave.rb

fix: deploy error about amazon S3 environment

---

app/uploaders/image_uploader.rb

fix: try to deploy without Rmagick

---

config/initializers/carrierwave.rb

fix: deploy error

---

app/models/code.rb
app/uploaders/image_uploader.rb
config/initializers/carrierwave.rb

ローカル環境でのS3アップロードを確認したため、本番環境にて動作検証

11 live preview

---

app/models/code.rb
app/models/favorite.rb
app/models/user.rb
db/migrate/20240826042848_create_favorites.rb
db/schema.rb
spec/factories/favorites.rb
spec/models/favorite_spec.rb

ER図をベースにFavoriteモデルの作成およびUserモデル、Codeモデルとのアソシエーションを追記しました。
ここまでの実装内容のレビューをお願いいたします！
**対応したこと**
**未対応**

Favoriteモデルの作成

---

app/assets/stylesheets/application.scss
app/javascript/application.js
app/javascript/editor/editor.bundle.js
app/javascript/editor/editor.mjs
app/views/codes/_editor.html.erb
app/views/codes/edit.html.erb
app/views/codes/index.html.erb
app/views/codes/new.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
db/migrate/20240830161848_change_column_default_to_codes.rb
db/schema.rb

viewの修正実施
・code index
・code editor

Fix view design

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

windowsにてform labelのサイズが変わってしまう現象を調整

fix: form label SVG's size at windows.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/iframe.css
app/javascript/editor/editor.bundle.js
app/javascript/editor/editor.mjs
app/javascript/editor/live_frame.js
app/views/codes/_editForm.html.erb
app/views/codes/_editorComponent.html.erb
app/views/codes/_showForm.html.erb
app/views/layouts/application.html.erb
package.json
tailwind.config.js

・CSSエディターを追加しました。
・tailwind CSSに対応しました。

Css editor

---

app/javascript/editor/editor.bundle.js
app/javascript/editor/live_frame.js
app/views/codes/_scriptForIframe.erb
app/views/codes/edit.html.erb
app/views/codes/new.html.erb
app/views/codes/show.html.erb
app/views/layouts/application.html.erb

tailwindのコードが本番環境で読み込まれない事象を改善

fix: tailwind code's link

---

app/javascript/application.js
app/javascript/editor/copyClipboard.js
app/javascript/editor/editor.bundle.js
app/javascript/editor/editor.mjs
app/views/codes/_editorComponent.html.erb
app/views/codes/_scriptForIframe.erb

18 code copy

---

app/controllers/codes_controller.rb
app/helpers/application_helper.rb
app/views/codes/index.html.erb

feat: add order switch for codes index

---

app/assets/stylesheets/application.scss
app/controllers/codes_controller.rb
app/javascript/editor/copyClipboard.js
app/javascript/editor/editor.bundle.js
app/javascript/editor/editor.mjs
app/views/codes/_editForm.html.erb
app/views/codes/_editorComponent.html.erb
app/views/codes/_showForm.html.erb

feat: add javascript editor

---

app/controllers/codes_controller.rb
app/javascript/controllers/code_title_edit_controller.js
app/models/code.rb
app/models/code_tag.rb
app/models/tag.rb
app/views/codes/_editForm.html.erb
app/views/codes/_showForm.html.erb
app/views/codes/index.html.erb
db/migrate/20240914064348_create_tags.rb
db/migrate/20240914064450_create_code_tags.rb
db/migrate/20240914110015_fix_unique_index_on_code_tags.rb
db/schema.rb
spec/factories/code_tags.rb
spec/factories/tags.rb
spec/models/code_tag_spec.rb
spec/models/tag_spec.rb

feat:add tag input

---

Gemfile
app/controllers/codes_controller.rb
app/views/codes/index.html.erb
app/views/layouts/_header.html.erb
config/locales/views/ja.yml
config/routes.rb

Collection code

---

Gemfile
Gemfile.lock
app/controllers/codes_controller.rb
app/models/code.rb
app/views/codes/index.html.erb

feat: add search form

---

app/controllers/codes_controller.rb
app/models/code.rb
app/models/tag.rb
app/models/user.rb
app/views/codes/index.html.erb

feat: user and tag search

---

Gemfile
app/assets/stylesheets/application.scss
app/controllers/users/omniauth_callbacks_controller.rb
app/models/sns_credential.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/initializers/devise.rb
config/initializers/omniauth.rb
config/locales/views/ja.yml
config/routes.rb
db/migrate/20240922135449_create_sns_credentials.rb
db/schema.rb
spec/factories/sns_credentials.rb
spec/models/sns_credential_spec.rb

30 omniauth
